# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
# События, которые запускают jobs
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

# jobs запускаются параллельно, если не указана последовательность
jobs:
  # Название job вы можете назвать как угодно
  scan:
    name: gitleaks
    # Операционная система в виртуальной машине, в которой запускаются процессы
    runs-on: ubuntu-latest
     # Шаги
    steps:
     # Actions от github: проверяет репозиторий, гит и т.д.
      - uses: actions/checkout@v3
        with: #    параметры
          fetch-depth: 0
      # Actions от github: проверяет репозиторий, гит и т.д.    
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.  

 # другая jobs
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      # это запуск команд в командной строке
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest Flask
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # запуск тестов из файла test_server.py
        pytest test_server.py
